springdoc:
    swagger-ui:
        path: /swagger-api.html
    api-docs:
        path: /api-docs

api:
  prefix: /api/v1


spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  data:
    mongodb:
      uri: mongodb://root:123456@localhost:27017/zola_db?authSource=admin
      username: root
      password: 123456
      host: localhost
      port: 27017
      database: zola_db
      authentication-database: admin
  messages:
    basename: i18n/messages



